[phases.setup]
nixPkgs = ['python311', 'pip', 'git']

[phases.build]
cmds = ['pip install -r requirements.txt']

[phases.start]
cmd = 'python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8080'